'use client'
import {useEffect,useState} from 'react'
import {ArrowDownToLine,Check,ChevronRight,Gem,Layers3,LayoutDashboard,Package,Plus,RefreshCw,Rocket,Settings2,ShieldCheck,ShoppingBag,Sparkles,UserRound,Wallet,X} from 'lucide-react'

declare global{interface Window{Telegram?:{WebApp:{initData:string;ready():void;expand():void;HapticFeedback?:{impactOccurred:(s:string)=>void};openLink:(u:string)=>void}}}}
type Product={id:number;title:string;description:string;price:number;icon:string;mode:'auto'|'manual'|'paused';delivery_content?:string;active:boolean}
type Me={user:{first_name:string;username?:string};balance:number;isAdmin:boolean}
const demoProducts:Product[]=[{id:1,title:'Launch Kit',description:'Чек-лист запуска Mini App и готовая структура проекта.',price:5,icon:'rocket',mode:'auto',active:true},{id:2,title:'Creator Pack',description:'30 шаблонов для продвижения Telegram-проекта.',price:12,icon:'layers',mode:'auto',active:true},{id:3,title:'Noxiss UI Kit',description:'Тёмный UI-набор для магазина и админ-панели.',price:25,icon:'gem',mode:'auto',active:true}]
const icons:any={rocket:Rocket,layers:Layers3,gem:Gem}
function authHeaders(){return {'Content-Type':'application/json','x-telegram-init-data':window.Telegram?.WebApp.initData||''}}
export default function Home(){
 const [tab,setTab]=useState<'store'|'orders'|'admin'>('store'),[products,setProducts]=useState<Product[]>(demoProducts),[me,setMe]=useState<Me>({user:{first_name:'Гость'},balance:0,isAdmin:false}),[selected,setSelected]=useState<Product|null>(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false)
 const live=typeof window!=='undefined'&&!!window.Telegram?.WebApp?.initData
 useEffect(()=>{const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();if(live)load()},[live])
 async function load(){try{const [m,p]=await Promise.all([fetch('/api/me',{headers:authHeaders()}),fetch('/api/products',{headers:authHeaders()})]);if(m.ok)setMe(await m.json());if(p.ok)setProducts(await p.json())}catch{}}
 async function buy(){if(!selected)return;setLoading(true);try{const r=await fetch('/api/orders',{method:'POST',headers:authHeaders(),body:JSON.stringify({productId:selected.id})});const d=await r.json();if(!r.ok)throw new Error(d.error);setNotice(d.delivery?`Выдано: ${d.delivery}`:'Заказ передан администратору');setSelected(null);load()}catch(e:any){setNotice(e.message||'Не удалось оформить заказ')}finally{setLoading(false)}}
 async function topup(){setLoading(true);try{const r=await fetch('/api/invoices',{method:'POST',headers:authHeaders(),body:JSON.stringify({amount:10})});const d=await r.json();if(!r.ok)throw new Error(d.error);window.Telegram?.WebApp.openLink(d.url)}catch(e:any){setNotice(e.message||'Откройте приложение в Telegram')}finally{setLoading(false)}}
 async function saveProduct(p:Product){const r=await fetch(`/api/admin/products/${p.id}`,{method:'PATCH',headers:authHeaders(),body:JSON.stringify(p)});if(r.ok){setNotice('Настройки выдачи сохранены');load()}else setNotice('Нет доступа администратора')}
 return <main><div className="ambient a1"/><div className="ambient a2"/><header><div className="brand"><div className="mark"><Sparkles size={20}/></div><div><b>Noxiss Store</b><small>digital goods</small></div></div><button className="avatar"><UserRound size={18}/></button></header>
 <section className="hero"><span className="eyebrow"><ShieldCheck size={14}/> secure mini app</span><h1>Цифровые продукты.<br/><em>Мгновенно.</em></h1><p>Выберите продукт, оплатите с внутреннего баланса и получите покупку автоматически.</p><div className="balance"><div><small>Ваш баланс</small><strong>${me.balance.toFixed(2)}</strong></div><button onClick={topup}><Plus size={17}/>Пополнить</button></div></section>
 <nav><button className={tab==='store'?'active':''} onClick={()=>setTab('store')}><ShoppingBag/>Магазин</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}><Package/>Заказы</button>{me.isAdmin&&<button className={tab==='admin'?'active':''} onClick={()=>setTab('admin')}><LayoutDashboard/>Админ</button>}</nav>
 {tab==='store'&&<section className="content"><div className="sectionTitle"><div><small>КАТАЛОГ</small><h2>Стартовая коллекция</h2></div><span>{products.length} продукта</span></div><div className="grid">{products.filter(p=>p.active).map((p,i)=>{const Icon=icons[p.icon]||Sparkles;return <article key={p.id} style={{animationDelay:`${i*80}ms`}}><div className="productTop"><div className="productIcon"><Icon/></div><span className={`status ${p.mode}`}>{p.mode==='auto'?'Автовыдача':p.mode==='manual'?'Вручную':'Пауза'}</span></div><h3>{p.title}</h3><p>{p.description}</p><div className="productBottom"><strong>${Number(p.price).toFixed(2)}</strong><button disabled={p.mode==='paused'} onClick={()=>{setSelected(p);window.Telegram?.WebApp.HapticFeedback?.impactOccurred('light')}}>Купить<ChevronRight size={17}/></button></div></article>})}</div></section>}
 {tab==='orders'&&<section className="empty"><div><Package/></div><h2>Заказы появятся здесь</h2><p>После покупки вы увидите статус и материалы для скачивания.</p></section>}
 {tab==='admin'&&me.isAdmin&&<section className="content"><div className="sectionTitle"><div><small>УПРАВЛЕНИЕ</small><h2>Режим выдачи</h2></div><Settings2/></div><div className="adminList">{products.map(p=><div className="adminRow" key={p.id}><div><b>{p.title}</b><small>${Number(p.price).toFixed(2)}</small></div><select value={p.mode} onChange={e=>saveProduct({...p,mode:e.target.value as Product['mode']})}><option value="auto">Автоматически</option><option value="manual">Вручную</option><option value="paused">Приостановить</option></select></div>)}</div></section>}
 <footer><span><ShieldCheck/>Telegram Protected</span><span>Noxiss © 2026</span></footer>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="sheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><div className="sheetIcon"><ShoppingBag/></div><small>ПОДТВЕРЖДЕНИЕ</small><h2>{selected.title}</h2><p>С баланса будет списано <b>${Number(selected.price).toFixed(2)}</b>. {selected.mode==='auto'?'Материалы откроются сразу после оплаты.':'Заказ будет передан администратору.'}</p><button className="primary" disabled={loading} onClick={buy}>{loading?<RefreshCw className="spin"/>:<><Check/>Оплатить ${Number(selected.price).toFixed(2)}</>}</button></div></div>}
 {notice&&<div className="toast" onClick={()=>setNotice('')}><Check/>{notice}</div>}
 {!live&&<div className="demo">Режим предпросмотра · покупки доступны в Telegram</div>}</main>
}
